// Generated by scripts/build-genome-map.mjs — do not edit by hand.
// Verdicts with a genotype are derived from the actual 23andMe file;
// verdicts without one come from the PharmCAT run on the same file.
// Chromosome lengths and gene loci are GRCh37 constants.

export type MarkerState = "finding" | "known" | "guarded" | "locked";

export interface GeneMarker {
  gene: string;
  posMb: number;
  state: MarkerState;
  label: string | null;
  verdict: string;
  genotype: string | null;
  rsid: string | null;
}

export interface ChromosomeData {
  name: string;
  lengthMb: number;
  called: number;
  markers: GeneMarker[];
}

export const TOTAL_CALLED = 632949;
export const INSIGHT_COUNT = 25;

export const CHROMOSOMES: ChromosomeData[] = [
  {
    "name": "1",
    "lengthMb": 249.25,
    "called": 51451,
    "markers": [
      {
        "gene": "MTHFR",
        "posMb": 11.86,
        "state": "known",
        "label": "Folate",
        "verdict": "Folate: you process it normally — no special supplementation story.",
        "genotype": "GG",
        "rsid": "rs1801133"
      }
    ]
  },
  {
    "name": "2",
    "lengthMb": 243.2,
    "called": 51068,
    "markers": [
      {
        "gene": "MCM6/LCT",
        "posMb": 136.61,
        "state": "known",
        "label": "Lactose",
        "verdict": "Lactose: your lactase likely switched off after childhood — most dairy will bother you.",
        "genotype": "GG",
        "rsid": "rs4988235"
      },
      {
        "gene": "UGT1A1",
        "posMb": 234.67,
        "state": "known",
        "label": null,
        "verdict": "Bilirubin: standard processing — no Gilbert's-syndrome tendency here.",
        "genotype": "CC",
        "rsid": "rs887829"
      }
    ]
  },
  {
    "name": "3",
    "lengthMb": 198.02,
    "called": 42353,
    "markers": []
  },
  {
    "name": "4",
    "lengthMb": 191.15,
    "called": 38812,
    "markers": [
      {
        "gene": "GC",
        "posMb": 72.61,
        "state": "known",
        "label": "Vitamin D",
        "verdict": "Vitamin D: typical binding-protein levels — supplement by lifestyle, not genetics.",
        "genotype": "TT",
        "rsid": "rs2282679"
      },
      {
        "gene": "ADH1B",
        "posMb": 100.24,
        "state": "known",
        "label": null,
        "verdict": "Alcohol: standard first-step metabolism.",
        "genotype": "CC",
        "rsid": "rs1229984"
      }
    ]
  },
  {
    "name": "5",
    "lengthMb": 180.92,
    "called": 36486,
    "markers": []
  },
  {
    "name": "6",
    "lengthMb": 171.12,
    "called": 43324,
    "markers": [
      {
        "gene": "TPMT",
        "posMb": 18.13,
        "state": "known",
        "label": null,
        "verdict": "Thiopurine medications: standard dosing (TPMT *1/*1).",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "HFE",
        "posMb": 26.09,
        "state": "known",
        "label": "Iron",
        "verdict": "Iron: no C282Y hemochromatosis variant — the main overload flag is clear.",
        "genotype": "GG",
        "rsid": "rs1800562"
      },
      {
        "gene": "HLA-A",
        "posMb": 29.91,
        "state": "locked",
        "label": null,
        "verdict": "Severe drug-reaction alleles — chips can't type HLA; sequencing can.",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "HLA-B",
        "posMb": 31.32,
        "state": "locked",
        "label": null,
        "verdict": "Severe drug-reaction alleles (abacavir, carbamazepine) — needs sequencing.",
        "genotype": null,
        "rsid": null
      }
    ]
  },
  {
    "name": "7",
    "lengthMb": 159.14,
    "called": 33724,
    "markers": [
      {
        "gene": "CYP3A5",
        "posMb": 99.27,
        "state": "known",
        "label": null,
        "verdict": "A few transplant medications: standard dosing (CYP3A5 non-expresser — most people are).",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "TAS2R38",
        "posMb": 141.67,
        "state": "known",
        "label": "Taste",
        "verdict": "Bitter taste: strong taster — brassicas and tonic water really are worse for you.",
        "genotype": "CC",
        "rsid": "rs713598"
      }
    ]
  },
  {
    "name": "8",
    "lengthMb": 146.36,
    "called": 31171,
    "markers": [
      {
        "gene": "NAT2",
        "posMb": 18.26,
        "state": "known",
        "label": null,
        "verdict": "Slow acetylator (NAT2) — matters for a few older drugs like isoniazid.",
        "genotype": null,
        "rsid": null
      }
    ]
  },
  {
    "name": "9",
    "lengthMb": 141.21,
    "called": 25938,
    "markers": []
  },
  {
    "name": "10",
    "lengthMb": 135.53,
    "called": 31657,
    "markers": [
      {
        "gene": "CYP2C19",
        "posMb": 96.52,
        "state": "finding",
        "label": "Meds",
        "verdict": "Intermediate metabolizer (*1/*2) — you clear escitalopram, citalopram and omeprazole slower than most. CPIC Level A.",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "CYP2C9",
        "posMb": 96.7,
        "state": "known",
        "label": null,
        "verdict": "Ibuprofen and warfarin: standard metabolism (CYP2C9 *1/*1).",
        "genotype": null,
        "rsid": null
      }
    ]
  },
  {
    "name": "11",
    "lengthMb": 135.01,
    "called": 31241,
    "markers": [
      {
        "gene": "FADS1",
        "posMb": 61.55,
        "state": "known",
        "label": null,
        "verdict": "Omega-3: intermediate conversion — fish or algae sources work better than flax.",
        "genotype": "GT",
        "rsid": "rs174537"
      },
      {
        "gene": "ACTN3",
        "posMb": 66.33,
        "state": "known",
        "label": "Muscle",
        "verdict": "Muscle type: one sprint copy, one endurance — the versatile middle.",
        "genotype": "CT",
        "rsid": "rs1815739"
      }
    ]
  },
  {
    "name": "12",
    "lengthMb": 133.85,
    "called": 28874,
    "markers": [
      {
        "gene": "SLCO1B1",
        "posMb": 21.33,
        "state": "known",
        "label": "Statins",
        "verdict": "Statins: no elevated muscle-pain risk — standard dosing if you ever need one.",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "ALDH2",
        "posMb": 112.24,
        "state": "known",
        "label": null,
        "verdict": "Alcohol flush: no ALDH2 variant — you don't go red.",
        "genotype": "GG",
        "rsid": "rs671"
      }
    ]
  },
  {
    "name": "13",
    "lengthMb": 115.17,
    "called": 21750,
    "markers": []
  },
  {
    "name": "14",
    "lengthMb": 107.35,
    "called": 19550,
    "markers": []
  },
  {
    "name": "15",
    "lengthMb": 102.53,
    "called": 18702,
    "markers": [
      {
        "gene": "CYP1A2",
        "posMb": 75.04,
        "state": "known",
        "label": "Caffeine",
        "verdict": "Caffeine: slow metabolizer — that 4pm espresso is still working at midnight.",
        "genotype": "CC",
        "rsid": "rs762551"
      }
    ]
  },
  {
    "name": "16",
    "lengthMb": 90.35,
    "called": 20036,
    "markers": [
      {
        "gene": "VKORC1",
        "posMb": 31.11,
        "state": "known",
        "label": null,
        "verdict": "Warfarin sensitivity: standard (VKORC1 reference).",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "MC1R",
        "posMb": 89.99,
        "state": "known",
        "label": "Sun",
        "verdict": "Sun: no red-hair-variant at R151C — typical burn risk from this gene.",
        "genotype": "CC",
        "rsid": "rs1805007"
      }
    ]
  },
  {
    "name": "17",
    "lengthMb": 81.2,
    "called": 19099,
    "markers": []
  },
  {
    "name": "18",
    "lengthMb": 78.08,
    "called": 17488,
    "markers": []
  },
  {
    "name": "19",
    "lengthMb": 59.13,
    "called": 14873,
    "markers": [
      {
        "gene": "CYP4F2",
        "posMb": 15.99,
        "state": "known",
        "label": null,
        "verdict": "Warfarin fine-tuning: one variant copy — you'd likely need a slightly higher dose.",
        "genotype": "CT",
        "rsid": "rs2108622"
      },
      {
        "gene": "RYR1",
        "posMb": 38.98,
        "state": "known",
        "label": null,
        "verdict": "Anesthesia: no malignant-hyperthermia flags at the positions read (RYR1 reference).",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "APOE",
        "posMb": 45.41,
        "state": "guarded",
        "label": "B12 · APOE",
        "verdict": "APOE affects Alzheimer's and heart risk. We read it, but don't show it unless you ask.",
        "genotype": null,
        "rsid": null
      },
      {
        "gene": "FUT2",
        "posMb": 49.21,
        "state": "known",
        "label": null,
        "verdict": "B12: secretor type — standard absorption.",
        "genotype": "GG",
        "rsid": "rs601338"
      }
    ]
  },
  {
    "name": "20",
    "lengthMb": 63.03,
    "called": 14592,
    "markers": []
  },
  {
    "name": "21",
    "lengthMb": 48.13,
    "called": 8441,
    "markers": []
  },
  {
    "name": "22",
    "lengthMb": 51.3,
    "called": 8983,
    "markers": [
      {
        "gene": "ADORA2A",
        "posMb": 24.84,
        "state": "known",
        "label": null,
        "verdict": "Caffeine sensitivity: high — the receptor side of why coffee hits you hard.",
        "genotype": "TT",
        "rsid": "rs5751876"
      },
      {
        "gene": "CYP2D6",
        "posMb": 42.52,
        "state": "locked",
        "label": null,
        "verdict": "Shapes 1 in 4 antidepressants and codeine — chips can't count gene copies; sequencing can.",
        "genotype": null,
        "rsid": null
      }
    ]
  },
  {
    "name": "X",
    "lengthMb": 155.27,
    "called": 15965,
    "markers": [
      {
        "gene": "G6PD",
        "posMb": 153.76,
        "state": "known",
        "label": null,
        "verdict": "G6PD: normal variant (B) — no hemolysis flags for the drugs it gates.",
        "genotype": null,
        "rsid": null
      }
    ]
  },
  {
    "name": "Y",
    "lengthMb": 59.37,
    "called": 3326,
    "markers": []
  },
  {
    "name": "MT",
    "lengthMb": 0.0166,
    "called": 4045,
    "markers": [
      {
        "gene": "MT-RNR1",
        "posMb": 0.001,
        "state": "locked",
        "label": null,
        "verdict": "Aminoglycoside-antibiotic hearing risk — needs full mitochondrial sequencing.",
        "genotype": null,
        "rsid": null
      }
    ]
  }
];
